ALTER TABLE `Post` ADD COLUMN `ogTitle` VARCHAR(255) NULL, ADD COLUMN `ogDescription` VARCHAR(500) NULL;
ALTER TABLE `Page` ADD COLUMN `ogTitle` VARCHAR(255) NULL, ADD COLUMN `ogDescription` VARCHAR(500) NULL, ADD COLUMN `ogImage` VARCHAR(1000) NULL;
