import { createHash, createHmac, randomBytes, timingSafeEqual, createCipheriv, createDecipheriv } from 'node:crypto'
import { getCookie, getHeader, getRequestIP, setCookie, deleteCookie, createError, type H3Event } from 'h3'
import { db } from './db'
import { UAParser } from 'ua-parser-js'
const SESSION='northstar_session'; const CSRF='northstar_csrf'
export const hash=(value:string)=>createHash('sha256').update(value).digest('hex')
export function clientHash(event:H3Event,value?:string){return createHmac('sha256',process.env.SESSION_SECRET||'development-only').update(value||getRequestIP(event,{xForwardedFor:process.env.TRUST_PROXY==='true'})||'unknown').digest('hex')}
export async function createSession(event:H3Event,adminId:string){const token=randomBytes(32).toString('base64url');const csrf=randomBytes(24).toString('base64url');await db.session.create({data:{tokenHash:hash(token),adminId,expiresAt:new Date(Date.now()+30*864e5),userAgent:getHeader(event,'user-agent')?.slice(0,500),ipHash:clientHash(event)}});const secure=process.env.NODE_ENV==='production';setCookie(event,SESSION,token,{httpOnly:true,secure,sameSite:'lax',path:'/',maxAge:30*86400});setCookie(event,CSRF,csrf,{httpOnly:false,secure,sameSite:'lax',path:'/',maxAge:30*86400});return csrf}
export async function requireSession(event:H3Event){const token=getCookie(event,SESSION);if(!token)throw createError({statusCode:401,statusMessage:'请先登录'});const session=await db.session.findUnique({where:{tokenHash:hash(token)},include:{admin:true}});if(!session||session.expiresAt<new Date()){if(session)await db.session.delete({where:{id:session.id}});throw createError({statusCode:401,statusMessage:'会话已过期'})}return session}
export async function requireAdmin(event:H3Event){return (await requireSession(event)).admin}
export function requireCsrf(event:H3Event){const origin=getHeader(event,'origin');if(origin){const parsed=new URL(origin);const host=getHeader(event,'x-forwarded-host')||getHeader(event,'host');if(parsed.host!==host)throw createError({statusCode:403,statusMessage:'Origin 校验失败'})}const cookie=getCookie(event,CSRF)||'';const header=getHeader(event,'x-csrf-token')||'';if(!cookie||!header||cookie.length!==header.length||!timingSafeEqual(Buffer.from(cookie),Buffer.from(header)))throw createError({statusCode:403,statusMessage:'CSRF 校验失败'})}
export async function logout(event:H3Event){const token=getCookie(event,SESSION);if(token)await db.session.deleteMany({where:{tokenHash:hash(token)}});deleteCookie(event,SESSION,{path:'/'});deleteCookie(event,CSRF,{path:'/'})}
const buckets=new Map<string,{count:number;reset:number}>();export function rateLimit(event:H3Event,key:string,limit=10,windowMs=60_000){const id=`${key}:${clientHash(event)}`;const now=Date.now();const b=buckets.get(id);if(!b||b.reset<now){buckets.set(id,{count:1,reset:now+windowMs});return}if(b.count>=limit)throw createError({statusCode:429,statusMessage:'请求过于频繁'});b.count++}
function encryptionKey(){const secret=process.env.ENCRYPTION_SECRET;if(!secret||secret.length<32)throw createError({statusCode:500,statusMessage:'ENCRYPTION_SECRET 必须至少 32 个字符'});return createHash('sha256').update(secret).digest()}
export function encryptSecret(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);const ciphertext=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),ciphertext.toString('base64url')].join('.')}
export function decryptSecret(value:string){const [iv,tag,data]=value.split('.');const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv!,'base64url'));decipher.setAuthTag(Buffer.from(tag!,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data!,'base64url')),decipher.final()]).toString('utf8')}
export function sessionAgent(ua:string|null){const r=new UAParser(ua||'').getResult();return {browser:r.browser.name||'Unknown',os:r.os.name||'Unknown',device:r.device.type||'desktop'}}
